//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fabricacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fabricacao()
        {
            this.Estoque = new HashSet<Estoque>();
            this.ItensFabricacao = new HashSet<ItensFabricacao>();
        }
    
        public int Id { get; set; }
        public int IdMaquina { get; set; }
        public int IdPedido { get; set; }
        public int IdSuprimento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estoque> Estoque { get; set; }
        public virtual Maquina Maquina { get; set; }
        public virtual Pedido Pedido { get; set; }
        public virtual Suprimento Suprimento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItensFabricacao> ItensFabricacao { get; set; }
    }
}
