//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class makerbarEntities : DbContext
    {
        public makerbarEntities()
            : base("name=makerbarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Estoque> Estoque { get; set; }
        public virtual DbSet<Fabricacao> Fabricacao { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<ItensFabricacao> ItensFabricacao { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Maquina> Maquina { get; set; }
        public virtual DbSet<Pedido> Pedido { get; set; }
        public virtual DbSet<Suprimento> Suprimento { get; set; }
    }
}
