//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suprimento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Suprimento()
        {
            this.Fabricacao = new HashSet<Fabricacao>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public Nullable<int> PesoInicial { get; set; }
        public Nullable<int> PesoAtual { get; set; }
        public string Tipo { get; set; }
        public string Cor { get; set; }
        public Nullable<int> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fabricacao> Fabricacao { get; set; }
    }
}
